### ISSUE TITLE
skottiekit.wasm

### ISSUE THREAD

**Issue by wikipedia2008** [tommyy96/skottie-editor#14]
hello:
       how skottiekit.wasm to compile? I can`t see official document

**Comment by tommyy96** [comment]
Hi, you should be able to get it using npm ( link: https://www.npmjs.com/package/canvaskit-wasm ). 

There should be more information at the link on canvaskit-wasm specifically, but if you run into other issues, let me know and I’ll try to help.

**Comment by wikipedia2008** [comment]
Thank you very much
